/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import com.mysql.jdbc.Connection;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import Model.*;
import Connector.*;
/**
 *
 * @author victormanuel
 */
public class Alta_alumno extends javax.swing.JInternalFrame {

    Grado grado = new Grado();
    Grupo grupo = new Grupo();
    Alumno_consulta ac = new Alumno_consulta();
    String sexo_;
    
    /**
     * Creates new form Alta_alumno
     */
    public Alta_alumno() {
        initComponents();
        
        btn_registrar.setEnabled(false);
        
        
       // DefaultComboBoxModel CB_gd = new DefaultComboBoxModel(grado.mostrarGrado());
       // cbx_grado.setModel(CB_gd);
        
        DefaultComboBoxModel CB_gp = new DefaultComboBoxModel(grupo.mostrarGrupo());
        cbx_grupo.setModel(CB_gp);
        
        mostrarDatosConTableModel();
        validar();

        
    }
    public void validar(){
        
        if(txt_ap.getText().isEmpty()){
            lb_v_ap.setText("*Campo requerido");
         
        } else { 
            lb_v_ap.setText("");
        }
        
        if(txt_am.getText().isEmpty()){
            lb_v_am.setText("*Campo requerido");
        } else {
            lb_v_am.setText("");
        }
        
        
        if(txt_nombre.getText().isEmpty()){
            lb_v_nombre.setText("*Campo requerido");
        } else {
            lb_v_nombre.setText("");
        }
        
        
        if(txt_correo.getText().isEmpty()){
            lb_v_correo.setText("*Campo requerido");
        } else if (!txt_correo.getText().contains("@") || !txt_correo.getText().contains(".")) {
            lb_v_correo.setText("*Correo Invalido");
        } else {
            lb_v_correo.setText("");
        }
        
        
        if(txt_tutor.getText().isEmpty()){
            lb_v_tutor.setText("*Campo requerido");
        } else {
            lb_v_tutor.setText("");
        }
        
        
        if(txt_curp.getText().isEmpty()){
            lb_v_curp.setText("*Campo requerido");
        } else {
            lb_v_curp.setText("");
        }
        
        
       /* if(txt_sexo.getText().isEmpty()){
            lb_v_sexo.setText("*Campo requerido");
        } else {
            lb_v_sexo.setText("");
        }*/
        
        if(txt_edad.getText().isEmpty()){
        lbl_edad.setText("*Campo requerido");
        txt_grado.setText("");
        }
        else{
        lbl_edad.setText("");
        }
         
        if(txt_ap.getText().isEmpty() || txt_am.getText().isEmpty() || txt_edad.getText().isEmpty() ||
                txt_nombre.getText().isEmpty() || txt_correo.getText().isEmpty() ||
                txt_tutor.getText().isEmpty() || txt_curp.getText().isEmpty() ||
                 lb_v_correo.getText().equals("*Correo Invalido")){
                btn_registrar.setEnabled(false);
        }else {
                btn_registrar.setEnabled(true);
        }
    }
    
    
    public void validadcaracteres (java.awt.event.KeyEvent evento){
    
        if(evento.getKeyChar() >= 33 && evento.getKeyChar() <= 64 
                || evento.getKeyChar() >= 91 && evento.getKeyChar() <= 96
                || evento.getKeyChar() >= 123 && evento.getKeyChar() <= 208
                || evento.getKeyChar() >= 210 && evento.getKeyChar() <= 240
                || evento.getKeyChar() >= 242 && evento.getKeyChar() <= 255
                ){
        evento.consume();
        JOptionPane.showMessageDialog(null, "NO SE PERMITEN CARACTERES ESPECIALES","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_ap = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_am = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_curp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbx_grupo = new javax.swing.JComboBox<>();
        txt_tutor = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        lb_v_ap = new javax.swing.JLabel();
        lb_v_am = new javax.swing.JLabel();
        lb_v_nombre = new javax.swing.JLabel();
        lb_v_curp = new javax.swing.JLabel();
        lb_v_sexo = new javax.swing.JLabel();
        lb_v_tutor = new javax.swing.JLabel();
        lb_v_correo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        lbl_edad = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_grado = new javax.swing.JTextField();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_alumno = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Registro de Alumnos");
        setMinimumSize(new java.awt.Dimension(800, 450));
        setNormalBounds(new java.awt.Rectangle(0, 0, 107, 0));
        setPreferredSize(new java.awt.Dimension(1181, 598));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1161, 313));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_apKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apKeyTyped(evt);
            }
        });
        jPanel2.add(txt_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 25, 170, -1));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel2.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 120, 170, -1));

        txt_am.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_amKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_amKeyTyped(evt);
            }
        });
        jPanel2.add(txt_am, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 71, 170, -1));

        jLabel1.setText("Apellido Paterno:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 28, -1, -1));

        jLabel2.setText("Apellido Materno:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 74, -1, -1));

        jLabel3.setText("Nombre (s):");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 123, -1, -1));

        jLabel4.setText("CURP:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 169, -1, -1));

        jLabel5.setText("Sexo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 223, -1, -1));

        txt_curp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_curpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_curpKeyTyped(evt);
            }
        });
        jPanel2.add(txt_curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 166, 170, -1));

        jLabel6.setText("Nombre del tutor:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 28, -1, -1));

        jLabel7.setText("Correo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 74, -1, -1));

        jLabel9.setText("Grupo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 146, -1, -1));

        jPanel2.add(cbx_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 167, 103, -1));

        txt_tutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tutorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tutorKeyTyped(evt);
            }
        });
        jPanel2.add(txt_tutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 25, 300, -1));

        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_correoKeyReleased(evt);
            }
        });
        jPanel2.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 71, 300, -1));

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, -1, -1));
        jPanel2.add(lb_v_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 25, -1, -1));
        jPanel2.add(lb_v_am, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 71, -1, -1));
        jPanel2.add(lb_v_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 120, -1, -1));
        jPanel2.add(lb_v_curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 166, -1, -1));
        jPanel2.add(lb_v_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 220, -1, -1));
        jPanel2.add(lb_v_tutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1059, 25, -1, -1));
        jPanel2.add(lb_v_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1059, 71, -1, -1));

        jLabel10.setText("Edad:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        txt_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_edadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_edadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_edadKeyTyped(evt);
            }
        });
        jPanel2.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 170, -1));
        jPanel2.add(lbl_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 264, -1, 30));

        jLabel11.setText("Grado:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        txt_grado.setEditable(false);
        txt_grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gradoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 110, -1));

        buttonGroup1.add(rb_m);
        rb_m.setText("M");
        rb_m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_mMouseClicked(evt);
            }
        });
        jPanel2.add(rb_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        buttonGroup1.add(rb_f);
        rb_f.setText("F");
        rb_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_fMouseClicked(evt);
            }
        });
        jPanel2.add(rb_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        table_alumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CURP", "Apellido Paterno", "Apellido Materno", "Nombre", "Sexo", "Edad", "Tutor", "Correo", "Grado", "Grupo"
            }
        ));
        jScrollPane1.setViewportView(table_alumno);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Alta de Alumnos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
       // Grado grado = (Grado) cbx_grado.getSelectedItem();
        Grupo grupo = (Grupo) cbx_grupo.getSelectedItem();
        
        int id=0, grado_=0, grupo_, edad_=0;
        String nombre_,ap_,am_,curp_, correo_, tutor_ , eliminar_ = "NO";
        
        try{
            //se obtienen los valores de la caja de texto y combo box
            ap_ = txt_ap.getText().toUpperCase();
            am_ = txt_am.getText().toUpperCase();
            nombre_ = txt_nombre.getText().toUpperCase();
            curp_ = txt_curp.getText().toUpperCase();
            //sexo_ = txt_sexo.getText().toUpperCase();
            correo_ = txt_correo.getText().toLowerCase();
            tutor_ = txt_tutor.getText().toUpperCase();       
            //grado_ = grado.getId();
            grupo_ = grupo.getId();
            edad_ = Integer.parseInt(txt_edad.getText());
        
            
            if(edad_ == 6){
             
             grado_ = 1;
            }
            
            if(edad_ == 7){
             
             grado_ = 2;
            }
            
            if(edad_ == 8){
               
              grado_ = 3;  
            }
            
            if(edad_ == 9){
              
              grado_ = 4; 
            }
            
            if(edad_ == 10){
              
              grado_ = 5;  
            }
            
            if(edad_ == 11){
              
              grado_ = 6;  
            }
            
            
            if(ac.existeAlumno(txt_curp.getText()) == 0){ //Revisa si el alumno existe o no
                //Se mandan los datos al metodo
                ac.registrarAlumno(1, id, ap_, am_, nombre_, sexo_, curp_, tutor_, correo_, grado_, grupo_, eliminar_, edad_);
            }else{
                JOptionPane.showMessageDialog(null, "ESTE ALUMNO YA EXISTE","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
            }
            
            
            
            
            
            
        }catch (Exception ex) {
	   JOptionPane.showMessageDialog(null,
	   "Error en el Ingreso de Datos, Revise si no hay campos sin rellenar", "Error",
	    JOptionPane.ERROR_MESSAGE);
        } finally{
        
           mostrarDatosConTableModel();
	   limpiar();
           validar();
        }
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_apKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apKeyTyped
      
        validadcaracteres(evt);
        
       
    }//GEN-LAST:event_txt_apKeyTyped

    private void txt_amKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amKeyTyped
       
        
        validadcaracteres(evt);
        
       
    }//GEN-LAST:event_txt_amKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        
        
        validadcaracteres(evt);
        
       
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_tutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tutorKeyTyped
    
        
        validadcaracteres(evt);
        
        
        
        
    }//GEN-LAST:event_txt_tutorKeyTyped

    private void txt_amKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_amKeyReleased

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void txt_curpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_curpKeyReleased
        // TODO add your handling code here:
        
       validar();
    }//GEN-LAST:event_txt_curpKeyReleased

    private void txt_tutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tutorKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_tutorKeyReleased

    private void txt_correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_correoKeyReleased

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
     
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_edadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_edadKeyReleased
        // TODO add your handling code here:
        validar();
        
         int edad_ = Integer.parseInt(txt_edad.getText());
        
        
        if(edad_ == 1){
        txt_grado.setText("");
        }
         
        if(edad_ == 6){
             txt_grado.setText("PRIMERO");
             
            }
            
            if(edad_ == 7){
             txt_grado.setText("SEGUNDO");  
             
            }
            
            if(edad_ == 8){
               txt_grado.setText("TERCERO");
               
            }
            
            if(edad_ == 9){
              txt_grado.setText("CUARTO");
               
            }
            
            if(edad_ == 10){
              txt_grado.setText("QUINTO");
              
            }
            
            if(edad_ == 11){
              txt_grado.setText("SEXTO");
             
            }
            
            if(edad_ >= 2 && edad_ < 6  || edad_ > 11){
            JOptionPane.showMessageDialog(null, "EDAD NO ACEPTADA","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
            txt_edad.setText("");
            txt_grado.setText("");
        }
    }//GEN-LAST:event_txt_edadKeyReleased

    private void txt_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_edadKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
       
       
        
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "NO SE PUEDE PROCESAR LA ENTRADA, ESCRIBA CARACTERES NUMERICOS","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        } 
        
 
    }//GEN-LAST:event_txt_edadKeyTyped

    private void txt_gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gradoActionPerformed

    private void txt_edadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_edadKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_edadKeyPressed

    private void txt_curpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_curpKeyTyped
        // TODO add your handling code here:
       // validadcaracteres(evt);
    }//GEN-LAST:event_txt_curpKeyTyped

    private void rb_mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_mMouseClicked
        // TODO add your handling code here:
        sexo_ = rb_m.getLabel();
    }//GEN-LAST:event_rb_mMouseClicked

    private void rb_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_fMouseClicked
        // TODO add your handling code here:
        sexo_ = rb_f.getLabel();
    }//GEN-LAST:event_rb_fMouseClicked

    private void txt_apKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_apKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_v_am;
    private javax.swing.JLabel lb_v_ap;
    private javax.swing.JLabel lb_v_correo;
    private javax.swing.JLabel lb_v_curp;
    private javax.swing.JLabel lb_v_nombre;
    private javax.swing.JLabel lb_v_sexo;
    private javax.swing.JLabel lb_v_tutor;
    private javax.swing.JLabel lbl_edad;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JTable table_alumno;
    private javax.swing.JTextField txt_am;
    private javax.swing.JTextField txt_ap;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_curp;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_grado;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_tutor;
    // End of variables declaration//GEN-END:variables

public void mostrarDatosConTableModel() {
	
        
                DefaultTableModel modelo = new DefaultTableModel();
                table_alumno.setModel(modelo);

               

                modelo.addColumn("CURP");
                modelo.addColumn("A. Paterno");
                modelo.addColumn("A. Materno");
                modelo.addColumn("Nombre");
                modelo.addColumn("Sexo");
                modelo.addColumn("Edad");
                modelo.addColumn("Tutor");
                modelo.addColumn("Correo");
                modelo.addColumn("Grado");
                modelo.addColumn("Grupo");
 
              

                 //Ordenar las columnas
                TableRowSorter<TableModel> ordena =new TableRowSorter<TableModel>(modelo);
                table_alumno.setRowSorter(ordena);
                               
               
		/* enviamos el objeto TableModel, como mandamos el objeto podemos
		  manipularlo desde el metodo */
		
                
                ac.consultaAlumnosConTableModel(modelo);

            
	}


public void limpiar(){
                txt_ap.setText("");
		txt_am.setText("");
                txt_nombre.setText("");
                txt_correo.setText("");
                txt_tutor.setText("");
                txt_curp.setText("");
		//txt_sexo.setText("");
                txt_edad.setText("");
                txt_grado.setText("");
               

}











}
