/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import com.mysql.jdbc.Connection;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import Model.*;
import Connector.*;

/**
 *
 * @author victormanuel
 */
public class Calif_3 extends javax.swing.JInternalFrame {

    Grado grado = new Grado();
    Grupo grupo = new Grupo();
    Mes mes = new Mes();
    Periodo periodo = new Periodo();
    Calificacion_consulta cali = new Calificacion_consulta();
    String  curpvieja_="";
    
    /**
     * Creates new form Alta_alumno
     */
    public Calif_3() {
        initComponents();
        
          btn_registrar.setEnabled(false);
//        btn_eliminar.setEnabled(false);


//Se mandan a traer los datos de las clases mes y trimestre, para rellenar los combobox con los datos de la base de datos
       DefaultComboBoxModel CB_m = new DefaultComboBoxModel(mes.mostrarMes());
       cbx_mes.setModel(CB_m);
        
        DefaultComboBoxModel CB_t = new DefaultComboBoxModel(periodo.mostrarPeriodo());
        cbx_trimestre.setModel(CB_t);
        
//        mostrarDatosConTableModel();
//        validar();

        
    }
    
    public void validarvacios(){
            if(txt_cal1.getText().isEmpty() || txt_cal2.getText().isEmpty() || txt_cal3.getText().isEmpty() || txt_curp.getText().isEmpty() ||
                txt_cal4.getText().isEmpty() || txt_cal5.getText().isEmpty() || txt_cal6.getText().isEmpty() 
                || txt_cal8.getText().isEmpty() || txt_ina.getText().isEmpty()){
                btn_registrar.setEnabled(false);
        }else {
                btn_registrar.setEnabled(true);
        }
}
    
     public void validar(java.awt.event.KeyEvent evento){
    //valida con los valores ascii
        if(evento.getKeyChar() >= 33 && evento.getKeyChar() <= 45
                || evento.getKeyChar() == 47
                || evento.getKeyChar() >= 58 && evento.getKeyChar() <= 122
                || evento.getKeyChar() >= 123 && evento.getKeyChar() <= 208
                || evento.getKeyChar() >= 210 && evento.getKeyChar() <= 240
                || evento.getKeyChar() >= 242 && evento.getKeyChar() <= 255
                ){
        evento.consume();
        JOptionPane.showMessageDialog(null, "NO SE PERMITEN CARACTERES ESPECIALES O LETRAS","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_curp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_alumno = new javax.swing.JTable();
        txt_buscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btn_salir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbx_mes = new javax.swing.JComboBox<>();
        cbx_trimestre = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_cal1 = new javax.swing.JTextField();
        txt_cal2 = new javax.swing.JTextField();
        txt_cal3 = new javax.swing.JTextField();
        txt_cal4 = new javax.swing.JTextField();
        txt_cal5 = new javax.swing.JTextField();
        txt_cal6 = new javax.swing.JTextField();
        txt_cal7 = new javax.swing.JTextField();
        txt_cal8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_ina = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Calificaciones 3°");
        setMinimumSize(new java.awt.Dimension(955, 468));
        setNormalBounds(new java.awt.Rectangle(0, 0, 107, 0));
        setPreferredSize(new java.awt.Dimension(955, 468));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(955, 468));

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setMinimumSize(new java.awt.Dimension(0, 0));
        Panel1.setPreferredSize(new java.awt.Dimension(955, 468));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setText("CURP:");
        Panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 40, 20));

        txt_curp.setEditable(false);
        txt_curp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_curp.setBorder(null);
        txt_curp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_curpActionPerformed(evt);
            }
        });
        txt_curp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_curpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_curpKeyTyped(evt);
            }
        });
        Panel1.add(txt_curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 20));

        table_alumno.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        table_alumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CURP", "Apellido Paterno", "Apellido Materno", "Nombre", "Grado", "Grupo"
            }
        ));
        table_alumno.setGridColor(new java.awt.Color(0, 0, 0));
        table_alumno.setSelectionBackground(new java.awt.Color(255, 255, 102));
        table_alumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_alumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_alumno);

        Panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 470, 128));

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscarKeyPressed(evt);
            }
        });
        Panel1.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setText("Buscar por apellido:");
        Panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        Panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 10));

        btn_salir.setBackground(new java.awt.Color(8, 59, 102));
        btn_salir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(204, 204, 204));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setToolTipText("");
        btn_salir.setBorder(null);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        Panel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 130, 40));

        btn_cancelar.setBackground(new java.awt.Color(8, 59, 102));
        btn_cancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(204, 204, 204));
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setToolTipText("");
        btn_cancelar.setBorder(null);
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseExited(evt);
            }
        });
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        Panel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 130, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar.png"))); // NOI18N
        Panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        btn_registrar.setBackground(new java.awt.Color(8, 59, 102));
        btn_registrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(204, 204, 204));
        btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregar.png"))); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.setToolTipText("");
        btn_registrar.setBorder(null);
        btn_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registrarMouseExited(evt);
            }
        });
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        Panel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 130, 38));

        jLabel8.setText("Mes:");
        Panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel12.setText("Trimestre:");
        Panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        Panel1.add(cbx_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 90, -1));

        Panel1.add(cbx_trimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 70, -1));

        jLabel1.setText("Educacion Sociemocional:");
        Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel2.setText("Matematicas:");
        Panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel3.setText("jLabel3");
        Panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jLabel5.setText("Ciencias naturales:");
        Panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel9.setText("Artes:");
        Panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel10.setText(" Formacion civica y etica:");
        Panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel11.setText("Vida saludable:");
        Panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel14.setText("Lengua materna:");
        Panel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel15.setText("Ingles:");
        Panel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        txt_cal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cal1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cal1KeyTyped(evt);
            }
        });
        Panel1.add(txt_cal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 60, -1));

        txt_cal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cal2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cal2KeyTyped(evt);
            }
        });
        Panel1.add(txt_cal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 60, -1));

        txt_cal3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cal3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cal3KeyTyped(evt);
            }
        });
        Panel1.add(txt_cal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 60, -1));

        txt_cal4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cal4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cal4KeyTyped(evt);
            }
        });
        Panel1.add(txt_cal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 60, -1));

        txt_cal5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cal5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cal5KeyTyped(evt);
            }
        });
        Panel1.add(txt_cal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 60, -1));

        txt_cal6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cal6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cal6KeyTyped(evt);
            }
        });
        Panel1.add(txt_cal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 60, -1));

        txt_cal7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cal7KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cal7KeyTyped(evt);
            }
        });
        Panel1.add(txt_cal7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 60, -1));

        txt_cal8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cal8KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cal8KeyTyped(evt);
            }
        });
        Panel1.add(txt_cal8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 60, -1));

        jLabel16.setText("Inasistencias:");
        Panel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 70, -1));

        txt_ina.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_inaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_inaKeyTyped(evt);
            }
        });
        Panel1.add(txt_ina, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 60, -1));

        jLabel17.setText("Observaciones:");
        Panel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 110, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        Panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 260, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        //validar();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarMouseExited

    private void btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarMouseEntered

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited

    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered

    }//GEN-LAST:event_btn_salirMouseEntered

    private void txt_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyPressed
        // TODO add your handling code here:
        String y;
        y = txt_buscar.getText();

        buscar(y);
    }//GEN-LAST:event_txt_buscarKeyPressed

    private void table_alumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_alumnoMouseClicked
        // TODO add your handling code here:
        int fila = table_alumno.getSelectedRow();
        
        txt_curp.setText(table_alumno.getValueAt(fila, 0).toString());
        
    }//GEN-LAST:event_table_alumnoMouseClicked

    private void txt_curpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_curpKeyTyped
        // TODO add your handling code here:
        // valida que solo entren 18 caracteres
        if(txt_curp.getText().length() >= 18){
            evt.consume();
        }
     
    }//GEN-LAST:event_txt_curpKeyTyped

    private void txt_curpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_curpKeyReleased
        // TODO add your handling code here:

//        validar();
    }//GEN-LAST:event_txt_curpKeyReleased

    private void btn_registrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseEntered

    }//GEN-LAST:event_btn_registrarMouseEntered

    private void btn_registrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registrarMouseExited

    }//GEN-LAST:event_btn_registrarMouseExited

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        Mes mes = (Mes) cbx_mes.getSelectedItem(); //selecciona el dato que este en el combobox
        Periodo periodo = (Periodo) cbx_trimestre.getSelectedItem(); //selecciona el dato que este en el combobox
        
        int id = 0, grado_ = 3, mes_, periodo_, inasistencia_;
        double cal1, cal2, cal3, cal4, cal5, cal6, cal7, cal8, cal9;
        String curp_;

        try {
        
            curp_ = txt_curp.getText();
            cal1 = Double.parseDouble(txt_cal1.getText());
            cal2 = Double.parseDouble(txt_cal2.getText());
            cal3 = Double.parseDouble(txt_cal3.getText());
            cal4 = Double.parseDouble(txt_cal4.getText());
            cal5 = Double.parseDouble(txt_cal5.getText());
            cal6 = Double.parseDouble(txt_cal6.getText());
            cal7 = Double.parseDouble(txt_cal7.getText());
            cal8 = Double.parseDouble(txt_cal8.getText());
            mes_ = mes.getId();
            periodo_ = periodo.getId();
            inasistencia_ = Integer.parseInt(txt_ina.getText());
            
            if(cal1<5 || cal1 >10){
                    JOptionPane.showMessageDialog(null,
	            "Error en el Ingreso de Calificaciones", "Error",
                    JOptionPane.ERROR_MESSAGE);
                    txt_cal1.setText("");
                    validarvacios();
                            
            }else if(cal2<5 || cal2 >10){
                    JOptionPane.showMessageDialog(null,
	            "Error en el Ingreso de Calificaciones", "Error",
                    JOptionPane.ERROR_MESSAGE);
                    txt_cal2.setText("");
                    validarvacios();
                            
            }else if(cal3<5 || cal3 >10){
                    JOptionPane.showMessageDialog(null,
	            "Error en el Ingreso de Calificaciones", "Error",
                    JOptionPane.ERROR_MESSAGE);
                    txt_cal3.setText("");
                    validarvacios();
                            
            }else if(cal4<5 || cal4 >10){
                    JOptionPane.showMessageDialog(null,
	            "Error en el Ingreso de Calificaciones", "Error",
                    JOptionPane.ERROR_MESSAGE);
                    txt_cal4.setText("");
                    validarvacios();
                            
            }else if(cal5<5 || cal5 >10){
                    JOptionPane.showMessageDialog(null,
	            "Error en el Ingreso de Calificaciones", "Error",
                    JOptionPane.ERROR_MESSAGE);
                    txt_cal5.setText("");
                    validarvacios();
                            
            }else if(cal6<5 || cal6 >10){
                    JOptionPane.showMessageDialog(null,
	            "Error en el Ingreso de Calificaciones", "Error",
                    JOptionPane.ERROR_MESSAGE);
                    txt_cal6.setText("");
                    validarvacios();
                            
            }else if(cal7<5 || cal7 >10){
                    JOptionPane.showMessageDialog(null,
	            "Error en el Ingreso de Calificaciones", "Error",
                    JOptionPane.ERROR_MESSAGE);
                    txt_cal7.setText("");
                    validarvacios();
                            
            }else if(cal8<5 || cal8 >10){
                    JOptionPane.showMessageDialog(null,
	            "Error en el Ingreso de Calificaciones", "Error",
                    JOptionPane.ERROR_MESSAGE);
                    txt_cal1.setText("");
                    validarvacios();
                            
            }
            else{
                
              cali.registrarCalificacion3(1, id, curp_, grado_, cal1, cal2, cal3, cal4, cal5, cal6, cal7, cal8, mes_, periodo_);
              cali.registrarInasistencia(1, id, curp_, grado_, inasistencia_, mes_, periodo_);
              limpiar();
              validarvacios();
            }
            
      
        }catch (Exception ex) {
	   JOptionPane.showMessageDialog(null,
	   "Error en el Ingreso de Datos, Revise si no hay campos sin rellenar", "Error",
	    JOptionPane.ERROR_MESSAGE);
        } 
    
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_curpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_curpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_curpActionPerformed

    private void txt_cal1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal1KeyTyped
        // TODO add your handling code here:

        validar(evt);
        
        if(txt_cal1.getText().length() >= 3){
        evt.consume();
        }
    }//GEN-LAST:event_txt_cal1KeyTyped

    private void txt_cal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal2KeyTyped
        // TODO add your handling code here:
         validar(evt);
        
        if(txt_cal2.getText().length() >= 3){
        evt.consume();
        }
    }//GEN-LAST:event_txt_cal2KeyTyped

    private void txt_cal3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal3KeyTyped
        // TODO add your handling code here:
         validar(evt);
         
        
        if(txt_cal3.getText().length() >= 3){
        evt.consume();
        }
    }//GEN-LAST:event_txt_cal3KeyTyped

    private void txt_cal4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal4KeyTyped
        // TODO add your handling code here:
         validar(evt);
        
        if(txt_cal4.getText().length() >= 3){
        evt.consume();
        }
    }//GEN-LAST:event_txt_cal4KeyTyped

    private void txt_cal5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal5KeyTyped
        // TODO add your handling code here:
       validar(evt);
        
        if(txt_cal5.getText().length() >= 3){
        evt.consume();
        }
    }//GEN-LAST:event_txt_cal5KeyTyped

    private void txt_cal6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal6KeyTyped
        // TODO add your handling code here:
    validar(evt);
        
        if(txt_cal6.getText().length() >= 3){
        evt.consume();
        }
    }//GEN-LAST:event_txt_cal6KeyTyped

    private void txt_cal7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal7KeyTyped
        // TODO add your handling code here:
        validar(evt);
        
        if(txt_cal7.getText().length() >= 3){
        evt.consume();
        }
    }//GEN-LAST:event_txt_cal7KeyTyped

    private void txt_cal8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal8KeyTyped
        // TODO add your handling code here:
         validar(evt);
        
        if(txt_cal8.getText().length() >= 3){
        evt.consume();
        }
    }//GEN-LAST:event_txt_cal8KeyTyped

    private void txt_inaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_inaKeyTyped
        // TODO add your handling code here:
        validar(evt);
        
    }//GEN-LAST:event_txt_inaKeyTyped

    private void txt_cal1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal1KeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_cal1KeyReleased

    private void txt_cal2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal2KeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_cal2KeyReleased

    private void txt_cal3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal3KeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_cal3KeyReleased

    private void txt_cal4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal4KeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_cal4KeyReleased

    private void txt_cal5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal5KeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_cal5KeyReleased

    private void txt_cal6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal6KeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_cal6KeyReleased

    private void txt_cal7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal7KeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_cal7KeyReleased

    private void txt_cal8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cal8KeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_cal8KeyReleased

    private void txt_inaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_inaKeyReleased
        // TODO add your handling code here:
        validarvacios();
    }//GEN-LAST:event_txt_inaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    public javax.swing.JButton btn_cancelar;
    public javax.swing.JButton btn_registrar;
    public javax.swing.JButton btn_salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_mes;
    private javax.swing.JComboBox<String> cbx_trimestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable table_alumno;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cal1;
    private javax.swing.JTextField txt_cal2;
    private javax.swing.JTextField txt_cal3;
    private javax.swing.JTextField txt_cal4;
    private javax.swing.JTextField txt_cal5;
    private javax.swing.JTextField txt_cal6;
    private javax.swing.JTextField txt_cal7;
    private javax.swing.JTextField txt_cal8;
    private javax.swing.JTextField txt_curp;
    private javax.swing.JTextField txt_ina;
    // End of variables declaration//GEN-END:variables


public void buscar(String x) {

        

                DefaultTableModel modelo = new DefaultTableModel();
                table_alumno.setModel(modelo);

                modelo.addColumn("CURP");
                modelo.addColumn("A. Paterno");
                modelo.addColumn("A. Materno");
                modelo.addColumn("Nombre");
                modelo.addColumn("Grado");
                modelo.addColumn("Grupo");
           
             
 
                 //Ordenar las columnas
                TableRowSorter<TableModel> ordena = new TableRowSorter<TableModel>(modelo);
                table_alumno.setRowSorter(ordena);

		     //manda los valores a la clase para que haga las instruciones sql
                cali.BuscarC3(modelo, x);
                
                
                

            
	}
public void limpiar(){
                txt_ina.setText("");
                txt_cal1.setText("");
		txt_cal2.setText("");
                txt_cal3.setText("");
                txt_curp.setText("");
                cbx_mes.setSelectedIndex(0);
                cbx_trimestre.setSelectedIndex(0);
                txt_cal4.setText("");
                txt_cal5.setText("");
                txt_cal6.setText("");
                txt_cal7.setText("");
                txt_cal8.setText("");
                txt_buscar.setText("");
                btn_registrar.setEnabled(false);
    
    
    

}


}
