/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import com.mysql.jdbc.Connection;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import Model.*;
import Connector.*;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author victormanuel
 */
public class Respaldos extends javax.swing.JInternalFrame {

    Grado grado = new Grado();
    Grupo grupo = new Grupo();
    Mes mes = new Mes();
    Conexion con = new Conexion();
    Periodo periodo = new Periodo();
    Calificacion_consulta cali = new Calificacion_consulta();
    String  curpvieja_="";
    
    /**
     * Creates new form Alta_alumno
     */
    public Respaldos() {
        initComponents();
        
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btn_buscar1 = new javax.swing.JButton();
        btn_cancelar1 = new javax.swing.JButton();
        txt_carpeta = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Respaldos");
        setMinimumSize(new java.awt.Dimension(955, 468));
        setNormalBounds(new java.awt.Rectangle(0, 0, 107, 0));
        setPreferredSize(new java.awt.Dimension(955, 468));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(955, 468));

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setMinimumSize(new java.awt.Dimension(0, 0));
        Panel1.setPreferredSize(new java.awt.Dimension(955, 468));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setBackground(new java.awt.Color(8, 59, 102));
        btn_salir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(204, 204, 204));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setToolTipText("");
        btn_salir.setBorder(null);
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        Panel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 130, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Exportar base de datos (copia de seguridad)");
        Panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jButton2.setText("Seleccionar carpeta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        btn_buscar1.setBackground(new java.awt.Color(8, 59, 102));
        btn_buscar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_buscar1.setForeground(new java.awt.Color(204, 204, 204));
        btn_buscar1.setText("Respaldar base de datos");
        btn_buscar1.setToolTipText("");
        btn_buscar1.setBorder(null);
        btn_buscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscar1MouseExited(evt);
            }
        });
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });
        Panel1.add(btn_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 160, 40));

        btn_cancelar1.setBackground(new java.awt.Color(8, 59, 102));
        btn_cancelar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_cancelar1.setForeground(new java.awt.Color(204, 204, 204));
        btn_cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"))); // NOI18N
        btn_cancelar1.setText("Cancelar respaldo");
        btn_cancelar1.setToolTipText("");
        btn_cancelar1.setBorder(null);
        btn_cancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelar1MouseExited(evt);
            }
        });
        btn_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar1ActionPerformed(evt);
            }
        });
        Panel1.add(btn_cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 170, 40));

        txt_carpeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_carpetaKeyPressed(evt);
            }
        });
        Panel1.add(txt_carpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 190, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited

    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered

    }//GEN-LAST:event_btn_salirMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        exportar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_buscar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar1MouseEntered

    private void btn_buscar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar1MouseExited

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        // TODO add your handling code here:
        String laruta = txt_carpeta.getText();
        String nombrescriptsql="/respaldoEscuela.sql"; //NOMBRE CON EL QUE SE GUARDARA EL RESPALDO
        String backup = "";
        try{
            if(laruta.trim().length()>0){
                backup = "C:/xampp/mysql/bin/mysqldump --routines -u"+con.getUsuario()+" -p"+con.getPass()+" -B "+con.getBD()+" -r "+laruta+nombrescriptsql;
                Runtime rtime = Runtime.getRuntime();
                rtime.exec(backup);
                JOptionPane.showMessageDialog(null,"La copia de seguridad de la base de datos se guardo con exito","Mensaje del sistema",JOptionPane.INFORMATION_MESSAGE);
            }else{
            JOptionPane.showMessageDialog(null, "Seleccione una carpeta para guardar el respaldo", "Mensaje de sistema", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void btn_cancelar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelar1MouseEntered

    private void btn_cancelar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelar1MouseExited

    private void btn_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelar1ActionPerformed

    private void txt_carpetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_carpetaKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_carpetaKeyPressed
          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    public javax.swing.JButton btn_buscar1;
    public javax.swing.JButton btn_cancelar1;
    public javax.swing.JButton btn_salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_carpeta;
    // End of variables declaration//GEN-END:variables

    public void exportar(){
   //metodo para abrir el explorador de archivos
        JFileChooser archivo=new JFileChooser();
        archivo.setDialogTitle("Seleccionar Carpeta");
        archivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int guardarscript = archivo.showSaveDialog(null);
        if(guardarscript==JFileChooser.APPROVE_OPTION){
            String ruta = archivo.getSelectedFile().getPath(); //selecciona la carpeta y la ruta 
            txt_carpeta.setText(ruta); //escribe la ruta sobre nuestra caja de texto
        }
    }


}